# Generated by Django 5.1 on 2024-08-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_pettycash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='date_issued',
            field=models.DateTimeField(),
        ),
    ]
