# Generated by Django 5.1 on 2024-10-11 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmi_pettycash', '0001_initial'),
        ('rmi_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmireceipt',
            name='petty_cash',
            field=models.OneToOneField(blank=True, help_text='Associated petty cash, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmi_receipt', to='rmi_pettycash.rmipettycash'),
        ),
    ]
