# Generated by Django 5.1 on 2024-12-16 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_paymentvouchers', '0001_initial'),
        ('tuition_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='tuition_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher', to='tuition_receipts.tuitionreceipt'),
        ),
    ]
