# Generated by Django 4.1.7 on 2024-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fund_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfundreceipt',
            name='receipt_number',
            field=models.CharField(blank=True, help_text='Optional receipt number for this transaction', max_length=50, null=True),
        ),
    ]
