# Generated by Django 4.1.7 on 2024-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rmi_pettycash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RMIReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('rmi_account', 'RMI Account')], default='rmi_account', max_length=50)),
                ('received_from', models.CharField(help_text='Name of the payer (could be a student or another entity)', max_length=100)),
                ('cash_bank', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=4)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount received', max_digits=10)),
                ('date', models.DateTimeField(help_text='Date of receipt')),
                ('petty_cash', models.OneToOneField(blank=True, help_text='Associated petty cash, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmi_receipt', to='rmi_pettycash.rmipettycash')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
