# Generated by Django 5.1 on 2024-09-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date and time the student was admitted (auto-filled)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(help_text="Student's date of birth (format: YYYY-MM-DDTHH:MM:SSZ)"),
        ),
    ]
