# Generated by Django 5.1 on 2024-10-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date the student was admitted'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateTimeField(help_text="Student's date of birth"),
        ),
    ]
