# Generated by Django 5.1 on 2024-08-28 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFundReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('school_fund_account', 'School Fund Account'), ('operations_account', 'Operations Account')], default='school_fund_account', max_length=50)),
                ('received_from', models.CharField(help_text='Name of the payer (could be a student or another entity)', max_length=100)),
                ('cash_bank', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=4)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount received', max_digits=10)),
                ('date', models.DateTimeField(help_text='Date of receipt')),
                ('student', models.ForeignKey(blank=True, help_text='The student associated with this receipt, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
