# Generated by Django 5.1 on 2024-08-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fund_pettycash', '0001_initial'),
        ('school_fund_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfundreceipt',
            name='petty_cash',
            field=models.OneToOneField(blank=True, help_text='Associated petty cash, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_fund_receipt', to='school_fund_pettycash.schoolfundpettycash'),
        ),
    ]
