# Generated by Django 5.1 on 2024-10-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fund_receipts', '0002_schoolfundreceipt_petty_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfundreceipt',
            name='account',
            field=models.CharField(choices=[('school_fund_account', 'School Fund Account')], default='school_fund_account', max_length=50),
        ),
    ]
