# Generated by Django 5.1 on 2024-08-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='operations_account', max_length=50)),
                ('received_from', models.CharField(max_length=100)),
                ('cash_bank', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=4)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rmi_fund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_voteheads', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
