# Generated by Django 5.1 on 2024-08-20 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_pettycash', '0002_alter_pettycash_date_issued'),
        ('operations_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationreceipt',
            name='petty_cash',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='operations_pettycash.pettycash'),
        ),
        migrations.AlterField(
            model_name='operationreceipt',
            name='other_voteheads',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='operationreceipt',
            name='rmi_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
