# Generated by Django 5.1 on 2024-10-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_pettycash', '0002_alter_pettycash_date_issued'),
        ('operations_receipts', '0003_alter_operationreceipt_petty_cash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationreceipt',
            name='petty_cash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='operations_pettycash.pettycash'),
        ),
    ]
