# Generated by Django 5.1 on 2024-10-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_receipts', '0005_alter_operationreceipt_other_voteheads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationreceipt',
            name='other_voteheads',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='operationreceipt',
            name='rmi_fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
