# Generated by Django 5.1 on 2024-10-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmi_paymentvoucher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rmipaymentvoucher',
            name='vote_head',
            field=models.CharField(choices=[('school_fund', 'School fund'), ('operations', 'Operations'), ('tuition', 'Tuition'), ('other_voteheads', 'Other Voteheads')], max_length=50),
        ),
    ]
