# Generated by Django 4.1.7 on 2024-12-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(help_text='Unique admission number for each student', max_length=20, unique=True)),
                ('first_name', models.CharField(help_text="Student's first name", max_length=50)),
                ('last_name', models.CharField(help_text="Student's last name", max_length=50)),
                ('date_of_birth', models.DateTimeField(help_text="Student's date of birth")),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], help_text="Student's gender", max_length=6)),
                ('admission_date', models.DateTimeField(auto_now_add=True, help_text='Date the student was admitted')),
                ('grade_class_level', models.CharField(choices=[('form1', 'Form 1'), ('form2', 'Form 2'), ('form3', 'Form 3'), ('form4', 'Form 4')], help_text='Class level of the student', max_length=5)),
                ('guardians_name', models.CharField(help_text="Guardian's full name", max_length=100)),
                ('guardians_phone_number', models.CharField(help_text="Guardian's phone number", max_length=15)),
            ],
        ),
    ]
