# Generated by Django 5.1 on 2024-08-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFundPaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='school_fund_account', max_length=255)),
                ('voucher_no', models.PositiveIntegerField()),
                ('payee_name', models.CharField(max_length=255)),
                ('particulars', models.TextField()),
                ('amount_shs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=50)),
                ('total_amount_in_words', models.CharField(max_length=255)),
                ('prepared_by', models.CharField(max_length=255)),
                ('authorised_by', models.CharField(max_length=255)),
                ('vote_head', models.CharField(max_length=255)),
                ('vote_details', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
