# Generated by Django 5.1 on 2024-10-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_receipts', '0004_alter_operationreceipt_petty_cash'),
        ('school_fund_paymentvouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfundpaymentvoucher',
            name='operation_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_fund_voucher', to='operations_receipts.operationreceipt'),
        ),
        migrations.AlterField(
            model_name='schoolfundpaymentvoucher',
            name='vote_head',
            field=models.CharField(choices=[('rmi', 'RMI'), ('school_fund', 'School Fund'), ('tuition', 'Tuition'), ('other_voteheads', 'Other Voteheads')], max_length=50),
        ),
    ]
