# Generated by Django 5.1 on 2024-10-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fund_paymentvouchers', '0002_schoolfundpaymentvoucher_operation_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfundpaymentvoucher',
            name='vote_head',
            field=models.CharField(choices=[('rmi', 'RMI'), ('operations', 'Operations'), ('tuition', 'Tuition'), ('other_voteheads', 'Other Voteheads')], max_length=50),
        ),
    ]
