# Generated by Django 5.1 on 2024-12-11 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tuition_pettycash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('tuition_account', 'Tuition Account')], default='tuition_account', max_length=50)),
                ('received_from', models.CharField(help_text='Name of the payer (could be a student or another entity)', max_length=100)),
                ('cash_bank', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=4)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount received', max_digits=10)),
                ('date', models.DateTimeField(help_text='Date of receipt')),
                ('petty_cash', models.OneToOneField(blank=True, help_text='Associated petty cash, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_receipt', to='tuition_pettycash.tuitionpettycash')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
