# Generated by Django 5.1 on 2024-12-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmi_receipts', '0001_initial'),
        ('school_fund_paymentvouchers', '0001_initial'),
        ('tuition_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfundpaymentvoucher',
            name='rmi_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_fund_payment_voucher', to='rmi_receipts.rmireceipt'),
        ),
        migrations.AddField(
            model_name='schoolfundpaymentvoucher',
            name='tuition_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_fund_voucher', to='tuition_receipts.tuitionreceipt'),
        ),
    ]
