# Generated by Django 4.1.7 on 2025-01-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fund_paymentvouchers', '0002_schoolfundpaymentvoucher_rmi_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfundpaymentvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque number, if applicable', max_length=255, null=True),
        ),
    ]
