# Generated by Django 5.1 on 2024-12-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmi_paymentvoucher', '0001_initial'),
        ('school_fund_receipts', '0001_initial'),
        ('tuition_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmipaymentvoucher',
            name='school_fund_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmi_payment_voucher', to='school_fund_receipts.schoolfundreceipt'),
        ),
        migrations.AddField(
            model_name='rmipaymentvoucher',
            name='tuition_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmi_payment_voucher', to='tuition_receipts.tuitionreceipt'),
        ),
    ]
