# Generated by Django 4.1.7 on 2025-01-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmi_paymentvoucher', '0002_rmipaymentvoucher_school_fund_receipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rmipaymentvoucher',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
