# Generated by Django 5.1 on 2024-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_bankcharges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcharges',
            name='charge_date',
            field=models.DateTimeField(),
        ),
    ]
