# Generated by Django 4.1.7 on 2024-12-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOpeningBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, help_text='The opening balance amount for the student', max_digits=10)),
                ('date_recorded', models.DateField(help_text='Date when the opening balance was recorded')),
                ('student', models.ForeignKey(help_text='The student associated with this opening balance', on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
