# Generated by Django 5.1 on 2024-10-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_paymentvouchers', '0003_alter_paymentvoucher_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='vote_head',
            field=models.CharField(choices=[('rmi', 'RMI'), ('school_fund', 'School Fund'), ('tuition', 'Tuition'), ('other_voteheads', 'Other Voteheads')], max_length=50),
        ),
    ]
