# Generated by Django 5.1 on 2024-10-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_paymentvouchers', '0004_alter_paymentvoucher_vote_head'),
        ('school_fund_receipts', '0003_alter_schoolfundreceipt_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='school_fund_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_voucher', to='school_fund_receipts.schoolfundreceipt'),
        ),
    ]
