# Generated by Django 4.1.7 on 2024-10-15 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tuition_pettycash', '0001_initial'),
        ('tuition_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionreceipt',
            name='petty_cash',
            field=models.OneToOneField(blank=True, help_text='Associated petty cash, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuition_receipt', to='tuition_pettycash.tuitionpettycash'),
        ),
    ]
